services:
  postgres:
    image: postgres:13
    container_name: fjordflowhub-postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: freights
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  mongodb:
    image: mongo:latest
    container_name: fjordflowhub-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh", # must be mongosh not a just mongo
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: fjordflowhub-rabbitmq
    ports:
      - "5672:5672"   # Sending msg port (MassTransit)
      - "15672:15672" # Web control panel port
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s # wait until 15 seconds after container startup
  freight-svc:
    image: fjordflowhub/freight-svc:latest
    container_name: fjordflowhub-freight-svc
    build:
      context: .
      dockerfile: src/FreightService/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;http://+:7777
      - RabbitMq__Host=rabbitmq # must be the same as rabbitmq service
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=devuser;Password=devpassword;Database=freights # must be the same as postgres service
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2 # as per appsettings
      - Kestrel__Endpoints__Grpc__Url=http://+:7777 # as per appsettings
      - Kestrel__Endpoints__WebApi__Protocols=Http1 # as per appsettings
      - Kestrel__Endpoints__WebApi__Url=http://+:80 # as per appsettings
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
  search-svc:
    image: fjordflowhub/search-svc:latest
    container_name: fjordflowhub-search-svc
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq # must be the same as rabbitmq service
      - ConnectionStrings__MongoDbConnection=mongodb://root:password@mongodb:27017
      - FreightServiceUrl=http://freight-svc
    ports:
      - "7002:80"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  identity-svc:
    image: fjordflowhub/identity-svc:latest
    container_name: fjordflowhub-identity-svc
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - IssuerUri=https://identity.flowfjordhub.local
      - ClientAppUri=https://app.flowfjordhub.local
      # Connect to the same postgres container but use 'identity' database
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=devuser;Password=devpassword;Database=identity
      - VIRTUAL_HOST=identity.flowfjordhub.local
    depends_on:
      postgres:
        condition: service_healthy
  gateway-svc:
    image: fjordflowhub/gateway-svc:latest
    container_name: fjordflowhub-gateway-svc
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=https://app.flowfjordhub.local
      - VIRTUAL_HOST=api.flowfjordhub.local
    depends_on:
      identity-svc:
        condition: service_started
      freight-svc:
        condition: service_started
      search-svc:
        condition: service_started 
  bid-svc:
    image: fjordflowhub/bid-svc:latest
    container_name: fjordflowhub-bid-svc
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq # must be the same as rabbitmq service
      - ConnectionStrings__BidDbConnection=mongodb://root:password@mongodb:27017
      - IdentityServiceUrl=http://identity-svc
      - GrpcFreight=http://freight-svc:7777
    ports:
      - "7003:80"
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy 
  notify-svc:
    image: fjordflowhub/notify-svc:latest
    container_name: fjordflowhub-notify-svc
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:80
    depends_on:
      rabbitmq:
        condition: service_started
  client:
    image: fjordflowhub/client:latest
    container_name: fjordflowhub-client
    build:
      context: .
      dockerfile: client/Dockerfile   
      args:
        # Add these environment variables!
        - NEXT_PUBLIC_NOTIFY_URL=http://localhost:6001/notifications 
    environment:
      - AUTH_SECRET="eVxkT1ZCKNGj7gSSXKU2IJ86O01Tc65m/T8N8ywqTBw="
      - API_URL=http://gateway-svc/
      - IDENTITY_URL=https://identity.flowfjordhub.local
      - IDENTITY_URL_INTERNAL=http://identity-svc
      - AUTH_URL=https://app.flowfjordhub.local
      - AUTH_URL_INTERNAL=http://client:3000
      - VIRTUAL_HOST=app.flowfjordhub.local
      - VIRTUAL_PORT=3000
      - AUTH_TRUST_HOST=true
    volumes:
      - /var/lib/web/data
    depends_on:
      gateway-svc:
        condition: service_started  
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs
volumes:
  pgdata:
  mongodata: