import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import NavBar from "./nav/NavBar";
import SignalRProvider from "./providers/SignalRProvider";

export const metadata: Metadata = {
  title: "Fjord-Flow-Hub",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ToastContainer
            position="bottom-right"
            hideProgressBar
            theme="colored"
          />
          <NavBar />
          <main className="container mx-auto px-5 pt-10">
            <SignalRProvider>{children}</SignalRProvider>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
