import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import QueryProvider from "./providers/QueryProvider";

export const metadata: Metadata = {
  title: "Fjord-Flow-Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <NavBar />
          <main className="container mx-auto px-5 pt-10">{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
